### ISSUE TITLE
Errors in the sample code

### ISSUE THREAD

**Issue by grid-jha** [Krutik6/TimiRGeN#3]
Dear TimiRGen authors,

I had some troubles to run with the sample code and sample data.
I'm stuck at the clustering. I think that the "percent" matrix has problems.
Do you have an idea?

> library(org.Mm.eg.db)
Loading required package: AnnotationDbi

> library(org.Hs.eg.db)

>
> setwd("/home/jisu/projects/p6_miRNA_network/data")
>
> data("mm_miR")
> data("mm_mRNA")
>
>
> MAE <- startObject(mm_miR, mm_mRNA)
> MAE <- getIdsMir(MAE = MAE, assay(MAE, 1), orgDB = org.Mm.eg.db, miRPrefix = "mmu")
> MAE <- getIdsMrna(MAE = MAE, assay(MAE, 2), mirror = "useast", species = "mmusculus", orgDB = org.Mm.eg.db)
[1] "BiomaRt server connection was established."
>
> MAE <- combineGenes(MAE = MAE, miR_data = assay(MAE, 1), assay(MAE, 2))
>
> MAE <- genesList(MAE = MAE, method = "c", genetic_data = assay(MAE, 9), timeString = "D")
>
> MAE <- significantVals(MAE = MAE, method = "c", geneList = metadata(MAE)[[1]], maxVal = 0.05, stringVal = "adjPVal")
>
> MAE <- addIds(MAE = MAE, method = "c", filtered_genelist = metadata(MAE)[[2]], miR_IDs = assay(MAE, 3), mRNA_IDs = assay(MAE, 7))
>
> MAE <- eNames(MAE = MAE, method = "c", gene_IDs = metadata(MAE)[[3]])
>
> MAE2 <- MultiAssayExperiment()
>
> MAE2 <- dloadGmt(MAE = MAE2, species = "Mus musculus")
trying URL 'http://data.wikipathways.org/current/gmt/wikipathways-20211010-gmt-Mus_musculus.gmt'
Content type 'unknown' length 86226 bytes (84 KB)
==================================================
downloaded 84 KB

> savePlots(largeList = metadata(MAE2)[[1]], maxInt = 5, fileType = "jpeg")
Error in h(simpleError(msg, call)) :
  error in evaluating the argument 'x' in selecting a method for function 'head': subscript out of bounds
>
> MAE2 <- wikiList(MAE2, stringSpecies = "Mus musculus", stringSymbol = "L")
>
> MAE2 <- wikiMatrix(MAE = MAE2, ID_list = metadata(MAE)[[4]], wp_list = metadata(MAE2)[[2]])
Error in metadata(MAE2)[[2]] : subscript out of bounds
>
> MAE2 <- turnPercent(MAE = MAE2, wikiMatrix = assay(MAE2, 4))
Error in value[[3L]](cond) :
  'assay(<ExperimentList>, i="numeric", ...)' invalid subscript 'i'
error in evaluating the argument 'x' in selecting a method for function 'assay': subscript is out of bounds
>
> MAE2 <- createClusters(MAE = MAE2, method = "c", percentMatrix = assay(MAE2, 5), noClusters = 4, variance = 0.99)
Error in value[[3L]](cond) :
  'assay(<ExperimentList>, i="numeric", ...)' invalid subscript 'i'
error in evaluating the argument 'x' in selecting a method for function 'assay': subscript is out of bounds

> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /home/jisu/Rcore/R-4.1.1/lib/R/lib/libRblas.so
LAPACK: /home/jisu/Rcore/R-4.1.1/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats4    tcltk     stats     graphics  grDevices utils     datasets
[8] methods   base

other attached packages:
 [1] org.Hs.eg.db_3.14.0          org.Mm.eg.db_3.14.0
 [3] AnnotationDbi_1.55.1         TimiRGeN_1.3.03
 [5] MultiAssayExperiment_1.19.16 SummarizedExperiment_1.23.5
 [7] GenomicRanges_1.45.0         GenomeInfoDb_1.29.8
 [9] IRanges_2.27.2               S4Vectors_0.31.5
[11] MatrixGenerics_1.5.4         matrixStats_0.61.0
[13] Mfuzz_2.53.0                 DynDoc_1.71.0
[15] widgetTools_1.71.0           e1071_1.7-9
[17] Biobase_2.53.0               BiocGenerics_0.39.2

**Comment by Krutik6** [comment]
Hi glad to see the first error was resolved.

It's honestly quite hard to troubleshoot and replicate this error without more information. One thing I would say is 1328 pathways being excluded is quite a lot, and perhaps some of the pre-processing has been incorrect. 

Here `TimiRGeN` is looking at pathways (from Wikipathways) rather than individual genes. Could you include the `head(df)` of your miRNA and mRNA data please. 

It may also be worthwhile to look at the `percentMatrix` being generated. To pull assays out of a MAE object simply use `X <- MAE[[n]]`.

Best,
Krutik

**Comment by daft-punkk** [comment]
Good morning Krutik, I really appreciate your support.
I checked some code of functions, I found some weird results from this code;
I think that the "ID_list" or "metadata(MAE)[[4]]" calculation has a
problem.
Thank you so much !
Best regards,

ID_list = metadata(MAE)[[4]]; wp_list = metadata(MAE2)[[2]]

wmat <- sapply(wp_list, function(x) {
        sapply(ID_list, function(y) *sum(x %in% y))*
    })
    L <- lapply(wp_list, function(x) {
        length(x)
    })
 wmat2 <- as.data.frame(rbind(wmat, Total = unlist(L)))

wp_list[1]
$WP100
 [1] "102724197" "221357"    "2539"      "2678"      "2687"      "26873"
 [7] "2729"      "2730"      "2876"      "2877"      "2878"      "2879"
[13] "290"       "2936"      "2937"      "2938"      "2944"      "2946"
[19] "2952"      "2953"      "3417"      "728441"

# wmat
> assay(MAE2, 4)[1:5]
      WP100 WP106 WP107 WP111 WP117
D1       19    11    49    89    75
D2       19    11    49    89    75
D3       19    11    49    89    75
D4       19    11    49    89    75
D5       19    11    49    89    75
D6       19    11    49    89    75
Total    22    12    52   103   103

#wmat2
> assay(MAE2, 5)[1:5]
       WP100  WP106  WP107  WP111  WP117
D1     86.36  91.67  94.23  86.41  72.82
D2     86.36  91.67  94.23  86.41  72.82
D3     86.36  91.67  94.23  86.41  72.82
D4     86.36  91.67  94.23  86.41  72.82
D5     86.36  91.67  94.23  86.41  72.82
D6     86.36  91.67  94.23  86.41  72.82
Total 100.00 100.00 100.00 100.00 100.00

I failed to investigate why my data should have these results. I compared
these matrices of "mm_mRNA" and "mm_miR" in the sample code. Totally
different.

wp_list[1]
$WP100
 [1] "102724197" "221357"    "2539"      "2678"      "2687"      "26873"
 [7] "2729"      "2730"      "2876"      "2877"      "2878"      "2879"
[13] "290"       "2936"      "2937"      "2938"      "2944"      "2946"
[19] "2952"      "2953"      "3417"      "728441"

> names(ID_list)
[1] "D1" "D2" "D3" "D4" "D5" "D6"
> length(ID_list[[1]])
[1] 21122
> length(ID_list[[2]])
[1] 21122
> length(ID_list[[3]])
[1] 21122
> length(ID_list[[4]])
[1] 21122
> length(ID_list[[5]])
[1] 21122
> length(ID_list[[6]])
[1] 21122


This is the initial inputs, miR and mRNA. I tried to mimic as similar as
possible from the sample code (mm_miR, and mm_mRNA).


> head(miR,3)
                    D1.log2FoldChange       D1.padj D2.log2FoldChange
hsa-let-7a-2-3p            -1.0637782 9.779003e-116        -0.4664106
hsa-let-7a-3p              -0.1715312  0.000000e+00        -0.2997053
hsa-let-7a-5p/7c-5p        -0.2934334  3.688923e-23        -0.3410708
                          D2.padj D3.log2FoldChange       D3.padj
hsa-let-7a-2-3p     9.779003e-116        -0.1103546 9.779003e-116
hsa-let-7a-3p        0.000000e+00        -0.2540419  0.000000e+00
hsa-let-7a-5p/7c-5p  3.688923e-23        -0.3741078  3.688923e-23
                    D4.log2FoldChange       D4.padj D5.log2FoldChange
hsa-let-7a-2-3p            0.70592433 9.779003e-116        0.86415317
hsa-let-7a-3p             -0.01458706  0.000000e+00        0.08118807
hsa-let-7a-5p/7c-5p       -0.40380544  3.688923e-23       -0.39842928
                          D5.padj D6.log2FoldChange       D6.padj
hsa-let-7a-2-3p     9.779003e-116       0.979706903 9.779003e-116
hsa-let-7a-3p        0.000000e+00      -0.004676588  0.000000e+00
hsa-let-7a-5p/7c-5p  3.688923e-23      -0.386903424  3.688923e-23

> head(mRNA,3)
          D1.log2FoldChange      D1.padj D2.log2FoldChange      D2.padj
WASH7P           -0.8706762 3.530134e-91        -0.9240525 3.530134e-91
MIR6859-1        -0.6488382 8.292522e-25        -1.0091025 8.292522e-25
FAM138A           0.5016358 6.862003e-03         1.4921441 6.862003e-03
          D3.log2FoldChange      D3.padj D4.log2FoldChange      D4.padj
WASH7P           -0.8524954 3.530134e-91        -0.8990220 3.530134e-91
MIR6859-1        -0.8887331 8.292522e-25        -0.8180235 8.292522e-25
FAM138A           0.6325219 6.862003e-03         0.6307317 6.862003e-03
          D5.log2FoldChange      D5.padj D6.log2FoldChange      D6.padj
WASH7P           -0.8823724 3.530134e-91        -0.8897271 3.530134e-91
MIR6859-1        -0.7917853 8.292522e-25        -0.6693030 8.292522e-25
FAM138A           0.6884109 6.862003e-03         1.0081608 6.862003e-03


MAE2 <- wikiMatrix(MAE = MAE2, ID_list = metadata(MAE)[[4]], wp_list =
metadata(MAE2)[[2]])

used code
MAE <- startObject(miR, mRNA)
MAE <- getIdsMir(MAE = MAE, assay(MAE, 1), orgDB = org.Hs.eg.db, miRPrefix
= "hsa")
MAE <- getIdsMrna(MAE = MAE, assay(MAE, 2), mirror = "useast", species =
"hsapiens", orgDB = org.Hs.eg.db)
MAE <- combineGenes(MAE = MAE, miR_data = assay(MAE, 1), assay(MAE, 2))
MAE <- genesList(MAE = MAE, method = "c", genetic_data = assay(MAE, 9),
timeString = "D")
MAE <- significantVals(MAE = MAE, method = "c", geneList =
metadata(MAE)[[1]], maxVal = 0.05, stringVal = "padj")
MAE <- addIds(MAE = MAE, method = "c", filtered_genelist =
metadata(MAE)[[2]], miR_IDs = assay(MAE, 3), mRNA_IDs = assay(MAE, 7))
MAE <- eNames(MAE = MAE, method = "c", gene_IDs = metadata(MAE)[[3]])
MAE2 <- MultiAssayExperiment()
MAE2 <- dloadGmt(MAE = MAE2, species = "Homo sapiens")
MAE2 <- enrichWiki(MAE = MAE2, method = "c", ID_list = metadata(MAE)[[4]],
orgDB = org.Hs.eg.db, path_gene = assay(MAE2, 1), path_name = assay(MAE2,
2), ID = "ENTREZID", universe = assay(MAE2, 1)[[2]])
savePlots(largeList = metadata(MAE2)[[1]], maxInt = 5, fileType = "jpeg")
MAE2 <- wikiList(MAE2, stringSpecies = "Homo sapiens", stringSymbol = "L")
MAE2 <- wikiMatrix(MAE = MAE2, ID_list = metadata(MAE)[[4]], wp_list =
metadata(MAE2)[[2]])
MAE2 <- turnPercent(MAE = MAE2, wikiMatrix = assay(MAE2, 4))
MAE2 <- createClusters(MAE = MAE2, method = "c", percentMatrix =
assay(MAE2, 5), noClusters = 4, variance = 0.99)
1328 genes excluded.
Error in data[i, ] : subscript out of bounds
