### ISSUE TITLE
Drosophila issue (org.Dm.eg.db)

### ISSUE THREAD

**Issue by Tunc-Dabak** [Krutik6/TimiRGeN#4]
Dear Krutik,

I have 2 datasets for _Drosophila melanogaster_: 1 for miRNA (mm_miR) and 1 for mRNA (mm_mRNA). I tried to use "getIDsMir" function on our 'mm_miR' object after completing the MultiAssay Experiment step however I am getting an error "Error in .testForValidKeys(x, keys, keytype, fks) : None of the keys entered are valid keys for 'GENENAME'. Please use the keys method to see a listing of valid arguments.".

To overcome this issue, I have tried to look at the example data that you have used with Mus musculus however I could not see any difference.

Moreover, I have also increase the gene numbers for the "mm_miR" with some fake FC and p values, but I am still getting the same error. Below, I briefly written the R_script and their outputs:
>#########################################################################
`library(TimiRGeN)`
`library(org.Dm.eg.db)`
`mm_miR <- read.table("example_mir.txt")`
`mm_miR <- read.table("example_mir.txt")`
`mm_mRNA <- read.table("example_mRNA.txt")`
`MAE <- startObject(mm_miR, mm_mRNA)`
Warning messages:
1: 'ExperimentList' contains 'data.frame' or 'DataFrame',
  potential for errors with mixed data types 
`MAE <- getIdsMrna(MAE = MAE, assay(MAE, 2), mirror = "www", species = "dmelanogaster", orgDB = org.Dm.eg.db)`
[1] "BiomaRt server connection was established."
Warning messages:
1: 'ExperimentList' contains 'data.frame' or 'DataFrame',
  potential for errors with mixed data types 
`MAE <- getIdsMir(MAE = MAE, assay(MAE, 1), orgDB = org.Dm.eg.db, miRPrefix = "dme")`
Error in .testForValidKeys(x, keys, keytype, fks) : 
  None of the keys entered are valid keys for 'GENENAME'. Please use the keys method to see a listing of valid arguments.
#########################################################################
>>I could not figure out the last error (which I have received when I used a shorter "mm_miR" and now I tried it with a longer miRNA list which contains 299 genes but still I get the same error.).
Also tried it with the tool data as in the tutorial and it seems to work for the mammalian
[example_mir.txt](https://github.com/Krutik6/TimiRGeN/files/7507991/example_mir.txt)
[example_mRNA.txt](https://github.com/Krutik6/TimiRGeN/files/7507992/example_mRNA.txt)
[R_script.txt](https://github.com/Krutik6/TimiRGeN/files/7507993/R_script.txt)
.

**Comment by Krutik6** [comment]
Hi Tunc-Dubak,

Thank you for the detailed question. I do appreciate it. 
Unfortunately the tool was designed for mammalian research and this is the limiting factor here. 

To retrieve mRNA IDs, TimiRGeN uses biomaRt at the first instance, and only if the connection fails it uses clusterprofiler. This is why drosophilla data works with the getIdsMrna function.

The miRNA IDs are only retrieved from clusterProfiler. In hindsight I should have added biomaRt access to this function as a fail-safe, but this was never required when using human or mouse data. 

I have taken a note of this and will try to also implement drosophilla use into TimiRGeN, however it is unlikely to happen anytime soon, and most likely it will be implemented in the next few months. I understand as a student time is pressing so this is not ideal, sorry. 

One potential work around you could try is to make the miRNA annotations using biomaRt. 

Thanks,
Krutik

**Comment by Tunc-Dabak** [comment]
Hello Krutik,

Thank you for providing feedback and leaning on the issue. I really appreciate it. Moreover, I will follow your suggestion and try to work around it and if it succeeds I will update the post. Meanwhile, I will be following the updates on the tool and I hope it could be used to work on the drosophila data in the future as well.

I wish you success in your work.

Cheers,
Tunç
